In [5]:
import pandas as pd
import numpy as np

In [6]:
df =pd.read_csv("/content/netflix_titles.csv")

In [7]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7283,s7284,Movie,Legend of the Naga Pearls,Yang Lei,"Darren Wang, Zhang Tianai, Sheng Guansen, Simo...",China,"March 30, 2018",2017,TV-MA,108 min,"Action & Adventure, International Movies, Sci-...",A petty thief teams up with two bickering acco...
3814,s3815,Movie,ReMastered: The Lion's Share,Sam Cullman,NaN,NaN,"May 17, 2019",2019,TV-14,84 min,"Documentaries, Music & Musicals","After discovering the family of Solomon Linda,..."
2566,s2567,Movie,Bennett's War,Alex Ranarivelo,"Michael Roark, Trace Adkins, Ali Afshar, Allis...",United States,"May 2, 2020",2019,PG-13,94 min,"Dramas, Sports Movies",A medically discharged soldier attempts an imp...
6889,s6890,TV Show,Grand Designs,NaN,Kevin McCloud,United Kingdom,"August 1, 2019",2017,TV-14,2 Seasons,"British TV Shows, International TV Shows, Real...",Host Kevin McCloud presents people who take se...
4485,s4486,TV Show,The Hollywood Masters,NaN,NaN,United States,"October 23, 2018",2017,TV-MA,3 Seasons,Stand-Up Comedy & Talk Shows,Top Hollywood stars and directors open up abou...

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

Columns to keep in our recommendation system


release year, duration ,show id, type ,title, cast, director, rating, duration, description, listed in

**Columns to keep in final data**

title, release year, duration, show id  rest all in one column

Checking for duplicated items

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['listed_in'].value_counts()

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
                                                   ...
Action & Adventure, Cult Movies                       1
Action & Adventure, Comedies, Music & Musicals        1
Classic Movies, Horror Movies, Thrillers              1
Children & Family Movies, Classic Movies, Dramas      1
Cult Movies, Dramas, Thrillers                        1
Name: count, Length: 514, dtype: int64

Columns available to us in beginning

In [11]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [12]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [13]:
df.iloc[5].director

'Mike Flanagan'

In [14]:
df["cast"]

0                                                     NaN
1       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                     NaN
4       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
                              ...
8802    Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                                  NaN
8804    Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805    Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806    Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
Name: cast, Length: 8807, dtype: object

Removing the space between the names of one person

In [15]:
def no_space(text):
  if isinstance(text,str):
    no_space =text.split(" ")
    return "".join(no_space)
    return ''
df['cast']= df['cast'].apply(no_space)

Reducing the cast size to only 3 person

In [16]:
def get_three(text):
  if isinstance(text, str):


    cast_3 = [actor.strip() for actor in text.split(',') if actor.strip()]
    return ", ".join(cast_3[:3])
  return ''

df["cast"] = df["cast"].apply(get_three)

In [17]:
df['cast']

0
1                AmaQamata, KhosiNgema, GailMabalane
2              SamiBouajila, TracyGotoas, SamuelJouy
3
4                MayurMore, JitendraKumar, RanjanRaj
                            ...
8802    MarkRuffalo, JakeGyllenhaal, RobertDowneyJr.
8803
8804       JesseEisenberg, WoodyHarrelson, EmmaStone
8805              TimAllen, CourteneyCox, ChevyChase
8806    VickyKaushal, Sarah-JaneDias, RaaghavChanana
Name: cast, Length: 8807, dtype: object

## Reducing the space between the name of the director

In [18]:
def no_space(text):
  if isinstance(text,str):
    no_space =text.split(" ")
    return "".join(no_space)
    return ''
df['director']= df['director'].apply(no_space)

In [19]:
def no_space(text):
  if isinstance(text,str):
    no_space =text.split(" ")

    return "".join(no_space)
    return ''
df['newtitle']= df['title'].apply(no_space)

Their are lot of null values in cast and directors so we need to fill them up presently i am just filling it with title name

In [20]:
df['cast'] = df['cast'].fillna(df['newtitle'])
df['director'] = df['director'].mask(df['director'].isnull() | (df['director'] == 'None'), df['newtitle'])

In [21]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast              0
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
newtitle          0
dtype: int64

Removing the space between listed_in and

In [22]:
df['listed_in']

0                                           Documentaries
1         International TV Shows, TV Dramas, TV Mysteries
2       Crime TV Shows, International TV Shows, TV Act...
3                                  Docuseries, Reality TV
4       International TV Shows, Romantic TV Shows, TV ...
                              ...
8802                       Cult Movies, Dramas, Thrillers
8803               Kids' TV, Korean TV Shows, TV Comedies
8804                              Comedies, Horror Movies
8805                   Children & Family Movies, Comedies
8806       Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 8807, dtype: object

In [23]:
def no_space(text):
  if isinstance(text,str):
    no_space =text.split(" ")

    return "".join(no_space)
    return ''
df['listed_in']= df['listed_in'].apply(no_space)

In [24]:
df['listed_in']

0                                           Documentaries
1               InternationalTVShows,TVDramas,TVMysteries
2       CrimeTVShows,InternationalTVShows,TVAction&Adv...
3                                    Docuseries,RealityTV
4         InternationalTVShows,RomanticTVShows,TVComedies
                              ...
8802                          CultMovies,Dramas,Thrillers
8803                     Kids'TV,KoreanTVShows,TVComedies
8804                                Comedies,HorrorMovies
8805                       Children&FamilyMovies,Comedies
8806            Dramas,InternationalMovies,Music&Musicals
Name: listed_in, Length: 8807, dtype: object

# Overview of modified data

In [25]:

df['whitespace'] = (" ")
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,newtitle,whitespace
5048,s5049,TV Show,Coach Snoop,CoachSnoop,SnoopDogg,United States,"February 2, 2018",2018,TV-MA,1 Season,"Docuseries,RealityTV","Fueled by his own rough upbringing, Snoop Dogg...",CoachSnoop,
2337,s2338,TV Show,Twogether,Twogether,"LeeSeung-gi, JasperLiu",South Korea,"June 26, 2020",2020,TV-G,1 Season,"InternationalTVShows,KoreanTVShows,RealityTV",Paired together for an unforgettable trip acro...,Twogether,
7980,s7981,Movie,Sen Kimsin?,OzanAçıktan,"TolgaÇevik, KöksalEngür, PelinKörmükçü",Turkey,"March 10, 2017",2012,TV-14,102 min,"Comedies,InternationalMovies","Desperate for cash, klutzy private investigato...",SenKimsin?,
3571,s3572,TV Show,Hyperdrive,Hyperdrive,"RutledgeWood, MikeHill, MichaelBisping",United States,"August 21, 2019",2019,TV-PG,1 Season,RealityTV,Elite street racers from around the world test...,Hyperdrive,
7082,s7083,TV Show,Inside the Mossad,InsidetheMossad,,Israel,"January 29, 2019",2017,TV-14,1 Season,"Docuseries,InternationalTVShows","In this documentary, dozens of former agents f...",InsidetheMossad,
5706,s5707,Movie,Beauties of the Night,MaríaJoseCuevas,"OlgaBreeskin, LynMay, RossyMendoza",Mexico,"November 25, 2016",2016,TV-MA,92 min,"Documentaries,InternationalMovies","Back in the days of disco, Mexico had its own ...",BeautiesoftheNight,
2749,s2750,Movie,Wildling,FritzBöhm,"BelPowley, BradDourif, LivTyler",United States,"April 1, 2020",2018,R,93 min,"HorrorMovies,IndependentMovies,Sci-Fi&Fantasy",Confined to an attic for years by a man claimi...,Wildling,
5562,s5563,TV Show,Dave Chappelle,StanLathan,DaveChappelle,United States,"March 21, 2017",2017,TV-MA,1 Season,"Stand-UpComedy&TalkShows,TVComedies",Comedy icon Dave Chappelle makes his triumphan...,DaveChappelle,
6411,s6412,TV Show,Camp X,CampX,,Canada,"February 1, 2019",2014,TV-MA,1 Season,Docuseries,"Established during World War II, North America...",CampX,
2697,s2698,Movie,Tigertail,AlanYang,"TziMa, ChristineKo, Hong-ChiLee",United States,"April 10, 2020",2020,PG,91 min,Dramas,A man reflects on the lost love of his youth a...,Tigertail,

In [26]:
df['tags'] =df['director'] +df['whitespace']+ df['cast']+df['whitespace']+ df['listed_in'] +df['whitespace']+ df['description']+df['whitespace'] +df["rating"]
df.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,newtitle,whitespace,tags
8351,s8352,Movie,The Humanity Bureau,RobW.King,"NicolasCage, SarahLind, HughDillon",Canada,"December 18, 2018",2017,R,94 min,"Action&Adventure,Sci-Fi&Fantasy","In a dystopian, near-future United States, a d...",TheHumanityBureau,,"RobW.King NicolasCage, SarahLind, HughDillon A..."
3053,s3054,TV Show,Border Security: America's Front Line,BorderSecurity:America'sFrontLine,,Canada,"January 1, 2020",2018,TV-14,1 Season,"CrimeTVShows,InternationalTVShows,RealityTV",This reality series chronicles the behind-the-...,BorderSecurity:America'sFrontLine,,BorderSecurity:America'sFrontLine CrimeTVShow...
3575,s3576,TV Show,45 rpm,45rpm,"CarlosCuevas, GuiomarPuerta, IvánMarcos",Spain,"August 16, 2019",2019,TV-MA,1 Season,"InternationalTVShows,RomanticTVShows,Spanish-L...","In 1960s Madrid, music producer Guillermo Roja...",45rpm,,"45rpm CarlosCuevas, GuiomarPuerta, IvánMarcos ..."
2026,s2027,Movie,Poshter Girl,SameerPatil,"SonaleeKulkarni, HrishikeshJoshi, JitendraJoshi",India,"September 10, 2020",2016,TV-14,138 min,"Comedies,Dramas,InternationalMovies","In a town infamous for female infanticide, a y...",PoshterGirl,,"SameerPatil SonaleeKulkarni, HrishikeshJoshi, ..."
1819,s1820,Movie,Ghadi,AminDora,"GeorgesKhabbaz, LaraRain, EmmanuelKhairallah",Lebanon,"October 19, 2020",2013,TV-MA,101 min,"Comedies,Dramas,InternationalMovies",When the father of a boy with Down syndrome re...,Ghadi,,"AminDora GeorgesKhabbaz, LaraRain, EmmanuelKha..."
2563,s2564,Movie,Luccas Neto em: Acampamento de Férias 2,LucasMargutti,"LuccasNeto, GiovannaAlparone, JéssicaDiehl",Brazil,"May 4, 2020",2020,TV-G,81 min,"Children&FamilyMovies,Comedies,Music&Musicals",Luccas and his band of buddies make music and ...,LuccasNetoem:AcampamentodeFérias2,,"LucasMargutti LuccasNeto, GiovannaAlparone, Jé..."
8279,s8280,Movie,The Diabolical,AlistairLegrand,"AliLarter, ArjunGupta, MaxRose",United States,"August 1, 2018",2015,TV-MA,86 min,"HorrorMovies,Sci-Fi&Fantasy,Thrillers",Terrorized by unexplained disturbances and hor...,TheDiabolical,,"AlistairLegrand AliLarter, ArjunGupta, MaxRose..."
7282,s7283,Movie,Legend of the Guardians: The Owls of Ga'Hoole,ZackSnyder,"HelenMirren, GeoffreyRush, JimSturgess","United States, Australia","January 1, 2020",2010,PG,97 min,Children&FamilyMovies,"Soren, a barn owl kidnapped from his peaceful ...",LegendoftheGuardians:TheOwlsofGa'Hoole,,"ZackSnyder HelenMirren, GeoffreyRush, JimSturg..."
5178,s5179,TV Show,Fate/Apocrypha,Fate/Apocrypha,"NatsukiHanae, MaayaSakamoto, KoukiUchiyama",Japan,"November 7, 2017",2017,TV-MA,2 Seasons,"AnimeSeries,InternationalTVShows",The theft of the Greater Grail from Fuyuki Cit...,Fate/Apocrypha,,"Fate/Apocrypha NatsukiHanae, MaayaSakamoto, Ko..."
4793,s4794,Movie,Deewana Main Deewana,K.C.Bokadia,"Govinda, PriyankaChopra, KaderKhan",India,"July 1, 2018",2013,TV-14,107 min,"Comedies,Dramas,InternationalMovies",A man's instant attraction to a woman becomes ...,DeewanaMainDeewana,,"K.C.Bokadia Govinda, PriyankaChopra, KaderKhan..."

In [27]:
movies = df[['show_id','type','title','duration','release_year','tags']].copy()

In [28]:
movies['tags'] = movies['tags'].apply(lambda x: str(x).lower())

In [29]:
movies.shape

(8807, 6)

In [30]:
movies['tags'][1]

'blood&water amaqamata, khosingema, gailmabalane internationaltvshows,tvdramas,tvmysteries after crossing paths at a party, a cape town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth. tv-ma'

# Vectorization of the words

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
v =CountVectorizer(max_features=8807,stop_words='english')
vector=v.fit_transform(movies['tags']).toarray()

In [33]:
len(v.get_feature_names_out())

8807

Stemming

In [34]:
!pip install  nltk==3.9.4

Collecting nltk==3.9.4
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk==3.9.4) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk==3.9.4) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk==3.9.4) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk==3.9.4) (4.67.3)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 49.0 MB/s eta 0:00:00
Installing collected packages: nltk
  Attempting uninstall: nltk
    Found existing installation: nltk 3.9.1
    Uninstalling nltk-3.9.1:
      Successfully uninstalled nltk-3.9.1
Successfully installed nltk-3.9.4

In [35]:
import nltk
from  nltk.stem.porter import PorterStemmer
ps =PorterStemmer()

In [36]:
def stem(text):
  l = []
  for i in text.split(" "):
    l.append(ps.stem(i))
  return " ".join(l)

movies.loc[:, 'tags'] = movies['tags'].apply(stem)

In [37]:
movies['tags'][1]

'blood&wat amaqamata, khosingema, gailmabalan internationaltvshows,tvdramas,tvmysteri after cross path at a party, a cape town teen set out to prove whether a private-school swim star is her sister who wa abduct at birth. tv-ma'

In [38]:
v =CountVectorizer(max_features=8807,stop_words='english')
vector=v.fit_transform(movies['tags']).toarray()

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
similar =cosine_similarity(vector)

In [41]:
similar

array([[1.        , 0.        , 0.17213259, ..., 0.        , 0.1       ,
        0.31622777],
       [0.        , 1.        , 0.12309149, ..., 0.        , 0.        ,
        0.03768892],
       [0.17213259, 0.12309149, 1.        , ..., 0.0496904 , 0.        ,
        0.23814484],
       ...,
       [0.        , 0.        , 0.0496904 , ..., 1.        , 0.        ,
        0.        ],
       [0.1       , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.31622777, 0.03768892, 0.23814484, ..., 0.        , 0.        ,
        1.        ]])

In [42]:
sorted(list(enumerate(similar[0])),reverse=True,key = lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (2988, np.float64(0.4107919181288746)),
 (7364, np.float64(0.3952847075210474)),
 (7854, np.float64(0.3872983346207417)),
 (8691, np.float64(0.3813850356982369)),
 (8693, np.float64(0.3803194146278324)),
 (6579, np.float64(0.37796447300922725)),
 (4714, np.float64(0.37370465934182984)),
 (6216, np.float64(0.37370465934182984)),
 (1102, np.float64(0.3730019232961256)),
 (6726, np.float64(0.3614486980061245)),
 (8743, np.float64(0.35777087639996635)),
 (4754, np.float64(0.3577708763999663)),
 (4294, np.float64(0.3508232077228117)),
 (194, np.float64(0.35032452487268534)),
 (6047, np.float64(0.35)),
 (6133, np.float64(0.35)),
 (6327, np.float64(0.35)),
 (6491, np.float64(0.35)),
 (8384, np.float64(0.35)),
 (173, np.float64(0.34156502553198664)),
 (6038, np.float64(0.34156502553198664)),
 (7015, np.float64(0.34156502553198664)),
 (6056, np.float64(0.3415650255319866)),
 (8100, np.float64(0.3415650255319866)),
 (8547, np.float64(0.3415650255319866)),
 (4610, np.float64(0.3401680257083045)),
 (6313, np.float64(0.3401680257083045)),
 (1230, np.float64(0.3380617018914066)),
 (7682, np.float64(0.3380617018914066)),
 (160, np.float64(0.33541019662496846)),
 (8319, np.float64(0.3354101966249684)),
 (3848, np.float64(0.33371190623595726)),
 (8003, np.float64(0.33371190623595726)),
 (180, np.float64(0.3321819194149599)),
 (2271, np.float64(0.3321819194149599)),
 (2919, np.float64(0.3321819194149599)),
 (3004, np.float64(0.3321819194149599)),
 (8432, np.float64(0.3321819194149599)),
 (5480, np.float64(0.33084657994221345)),
 (2268, np.float64(0.32646431254950525)),
 (690, np.float64(0.32637668288410987)),
 (1469, np.float64(0.32637668288410987)),
 (1972, np.float64(0.32637668288410987)),
 (2191, np.float64(0.32637668288410987)),
 (7510, np.float64(0.32637668288410987)),
 (7210, np.float64(0.32539568672798425)),
 (1703, np.float64(0.32128773156099955)),
 (708, np.float64(0.31950482521134693)),
 (2385, np.float64(0.31950482521134693)),
 (6008, np.float64(0.31950482521134693)),
 (8580, np.float64(0.31950482521134693)),
 (4093, np.float64(0.316227766016838)),
 (1459, np.float64(0.31622776601683794)),
 (3460, np.float64(0.31622776601683794)),
 (4836, np.float64(0.31622776601683794)),
 (8806, np.float64(0.3162277660168379)),
 (3099, np.float64(0.31304951684997057)),
 (7520, np.float64(0.31304951684997057)),
 (2344, np.float64(0.3130495168499705)),
 (7594, np.float64(0.3130495168499705)),
 (7954, np.float64(0.3130495168499705)),
 (6517, np.float64(0.3113995776646092)),
 (179, np.float64(0.3077935056255462)),
 (182, np.float64(0.3077935056255462)),
 (1243, np.float64(0.3077935056255462)),
 (1886, np.float64(0.3077935056255462)),
 (2823, np.float64(0.3077935056255462)),
 (6329, np.float64(0.3077935056255462)),
 (6366, np.float64(0.3077935056255462)),
 (6907, np.float64(0.3077935056255462)),
 (7829, np.float64(0.3077935056255462)),
 (2913, np.float64(0.3069703067574603)),
 (5555, np.float64(0.3069703067574603)),
 (7071, np.float64(0.3069703067574603)),
 (7302, np.float64(0.3069703067574603)),
 (7509, np.float64(0.3069703067574603)),
 (2001, np.float64(0.30678599553894814)),
 (878, np.float64(0.30123203803835463)),
 (2584, np.float64(0.30123203803835463)),
 (2697, np.float64(0.30123203803835463)),
 (3408, np.float64(0.30123203803835463)),
 (4063, np.float64(0.30123203803835463)),
 (5512, np.float64(0.30123203803835463)),
 (6204, np.float64(0.30123203803835463)),
 (1761, np.float64(0.3)),
 (1912, np.float64(0.3)),
 (5008, np.float64(0.3)),
 (5916, np.float64(0.3)),
 (6311, np.float64(0.3)),
 (6777, np.float64(0.3)),
 (8200, np.float64(0.3)),
 (8627, np.float64(0.3)),
 (5197, np.float64(0.2988071523335984)),
 (1423, np.float64(0.2981423969999719)),
 (1444, np.float64(0.2981423969999719)),
 (735, np.float64(0.2958039891549808)),
 (879, np.float64(0.2958039891549808)),
 (1683, np.float64(0.2958039891549808)),
 (2110, np.float64(0.2958039891549808)),
 (2484, np.float64(0.2958039891549808)),
 (3093, np.float64(0.2958039891549808)),
 (3376, np.float64(0.2958039891549808)),
 (3917, np.float64(0.2958039891549808)),
 (4057, np.float64(0.2958039891549808)),
 (4370, np.float64(0.2958039891549808)),
 (4642, np.float64(0.2958039891549808)),
 (5570, np.float64(0.2958039891549808)),
 (6331, np.float64(0.2958039891549808)),
 (6888, np.float64(0.2958039891549808)),
 (4086, np.float64(0.29580398915498074)),
 (5778, np.float64(0.2940858488375231)),
 (634, np.float64(0.29277002188455997)),
 (1650, np.float64(0.29277002188455997)),
 (2370, np.float64(0.29277002188455997)),
 (4462, np.float64(0.29277002188455997)),
 (4525, np.float64(0.29277002188455997)),
 (5259, np.float64(0.29277002188455997)),
 (5831, np.float64(0.29277002188455997)),
 (6033, np.float64(0.29277002188455997)),
 (6164, np.float64(0.29277002188455997)),
 (6952, np.float64(0.29277002188455997)),
 (7005, np.float64(0.29277002188455997)),
 (7218, np.float64(0.29277002188455997)),
 (7595, np.float64(0.29277002188455997)),
 (8045, np.float64(0.29277002188455997)),
 (1066, np.float64(0.2927700218845599)),
 (3951, np.float64(0.2927700218845599)),
 (338, np.float64(0.2906591794880899)),
 (1528, np.float64(0.2906591794880899)),
 (5296, np.float64(0.2906591794880899)),
 (5953, np.float64(0.2906591794880899)),
 (5239, np.float64(0.28867513459481287)),
 (7161, np.float64(0.28867513459481287)),
 (144, np.float64(0.28603877677367767)),
 (1814, np.float64(0.28603877677367767)),
 (2450, np.float64(0.28603877677367767)),
 (3868, np.float64(0.28603877677367767)),
 (5165, np.float64(0.28603877677367767)),
 (5569, np.float64(0.28603877677367767)),
 (6445, np.float64(0.28603877677367767)),
 (7270, np.float64(0.28603877677367767)),
 (7398, np.float64(0.28603877677367767)),
 (905, np.float64(0.2857738033247041)),
 (2367, np.float64(0.2857738033247041)),
 (2623, np.float64(0.2857738033247041)),
 (4360, np.float64(0.2857738033247041)),
 (5306, np.float64(0.2857738033247041)),
 (787, np.float64(0.2811267651158746)),
 (848, np.float64(0.2811267651158746)),
 (1860, np.float64(0.2811267651158746)),
 (4115, np.float64(0.2811267651158746)),
 (5149, np.float64(0.2811267651158746)),
 (6802, np.float64(0.2811267651158746)),
 (685, np.float64(0.27975144247209416)),
 (1254, np.float64(0.27975144247209416)),
 (1387, np.float64(0.27975144247209416)),
 (2538, np.float64(0.27975144247209416)),
 (4537, np.float64(0.27975144247209416)),
 (5551, np.float64(0.27975144247209416)),
 (5945, np.float64(0.27975144247209416)),
 (7486, np.float64(0.27975144247209416)),
 (7898, np.float64(0.27975144247209416)),
 (8101, np.float64(0.27975144247209416)),
 (8356, np.float64(0.27975144247209416)),
 (8451, np.float64(0.27975144247209416)),
 (6574, np.float64(0.2795084971874737)),
 (6859, np.float64(0.2795084971874737)),
 (8387, np.float64(0.2795084971874737)),
 (8302, np.float64(0.27669929526473314)),
 (333, np.float64(0.2738612787525831)),
 (788, np.float64(0.2738612787525831)),
 (860, np.float64(0.2738612787525831)),
 (1144, np.float64(0.2738612787525831)),
 (1987, np.float64(0.2738612787525831)),
 (3544, np.float64(0.2738612787525831)),
 (4459, np.float64(0.2738612787525831)),
 (4937, np.float64(0.2738612787525831)),
 (5674, np.float64(0.2738612787525831)),
 (6283, np.float64(0.2738612787525831)),
 (6336, np.float64(0.2738612787525831)),
 (6733, np.float64(0.2738612787525831)),
 (7062, np.float64(0.2738612787525831)),
 (7316, np.float64(0.2738612787525831)),
 (7654, np.float64(0.2738612787525831)),
 (7686, np.float64(0.2738612787525831)),
 (8253, np.float64(0.2738612787525831)),
 (2731, np.float64(0.27247463045653303)),
 (4575, np.float64(0.27247463045653303)),
 (247, np.float64(0.2711630722733202)),
 (706, np.float64(0.2711630722733202)),
 (797, np.float64(0.2711630722733202)),
 (1341, np.float64(0.2711630722733202)),
 (2221, np.float64(0.2711630722733202)),
 (4877, np.float64(0.2711630722733202)),
 (5011, np.float64(0.2711630722733202)),
 (2738, np.float64(0.2684377460965796)),
 (5056, np.float64(0.2684377460965796)),
 (76, np.float64(0.2683281572999748)),
 (3310, np.float64(0.2683281572999748)),
 (4155, np.float64(0.2683281572999748)),
 (5461, np.float64(0.2683281572999748)),
 (5846, np.float64(0.2683281572999748)),
 (6029, np.float64(0.2683281572999748)),
 (8055, np.float64(0.2683281572999748)),
 (8219, np.float64(0.2683281572999748)),
 (8581, np.float64(0.2683281572999748)),
 (8749, np.float64(0.2683281572999748)),
 (1295, np.float64(0.2683281572999747)),
 (1312, np.float64(0.2683281572999747)),
 (3739, np.float64(0.2683281572999747)),
 (6597, np.float64(0.2683281572999747)),
 (2566, np.float64(0.26352313834736496)),
 (2585, np.float64(0.26352313834736496)),
 (5503, np.float64(0.26352313834736496)),
 (5676, np.float64(0.26352313834736496)),
 (5754, np.float64(0.26352313834736496)),
 (6294, np.float64(0.26352313834736496)),
 (6795, np.float64(0.26352313834736496)),
 (6898, np.float64(0.26352313834736496)),
 (7177, np.float64(0.26352313834736496)),
 (7927, np.float64(0.26352313834736496)),
 (1424, np.float64(0.2631174057921088)),
 (2591, np.float64(0.2631174057921088)),
 (4319, np.float64(0.2631174057921088)),
 (4786, np.float64(0.2631174057921088)),
 (5472, np.float64(0.2631174057921088)),
 (5863, np.float64(0.2631174057921088)),
 (6343, np.float64(0.2631174057921088)),
 (6727, np.float64(0.2631174057921088)),
 (7622, np.float64(0.2631174057921088)),
 (7712, np.float64(0.2631174057921088)),
 (7869, np.float64(0.2631174057921088)),
 (8197, np.float64(0.2631174057921088)),
 (8528, np.float64(0.2631174057921088)),
 (8569, np.float64(0.2631174057921088)),
 (4630, np.float64(0.25819888974716115)),
 (5699, np.float64(0.25819888974716115)),
 (7417, np.float64(0.25819888974716115)),
 (7734, np.float64(0.25819888974716115)),
 (872, np.float64(0.2581988897471611)),
 (989, np.float64(0.2581988897471611)),
 (2206, np.float64(0.2581988897471611)),
 (2510, np.float64(0.2581988897471611)),
 (2553, np.float64(0.2581988897471611)),
 (2698, np.float64(0.2581988897471611)),
 (2862, np.float64(0.2581988897471611)),
 (4802, np.float64(0.2581988897471611)),
 (7227, np.float64(0.2581988897471611)),
 (8234, np.float64(0.2581988897471611)),
 (1536, np.float64(0.2564945880212885)),
 (2437, np.float64(0.2564945880212885)),
 (2462, np.float64(0.2564945880212885)),
 (4353, np.float64(0.2564945880212885)),
 (4398, np.float64(0.2564945880212885)),
 (5824, np.float64(0.2564945880212885)),
 (5934, np.float64(0.2564945880212885)),
 (6333, np.float64(0.2564945880212885)),
 (7981, np.float64(0.2564945880212885)),
 (8183, np.float64(0.2564945880212885)),
 (8310, np.float64(0.2564945880212885)),
 (8469, np.float64(0.2564945880212885)),
 (8661, np.float64(0.2564945880212885)),
 (1264, np.float64(0.253546276418555)),
 (1381, np.float64(0.253546276418555)),
 (2425, np.float64(0.253546276418555)),
 (5061, np.float64(0.253546276418555)),
 (5698, np.float64(0.253546276418555)),
 (5777, np.float64(0.253546276418555)),
 (5904, np.float64(0.253546276418555)),
 (7431, np.float64(0.253546276418555)),
 (1938, np.float64(0.25354627641855493)),
 (3233, np.float64(0.25354627641855493)),
 (7208, np.float64(0.25354627641855493)),
 (3162, np.float64(0.25)),
 (255, np.float64(0.24999999999999997)),
 (2003, np.float64(0.24999999999999997)),
 (3192, np.float64(0.24999999999999997)),
 (3339, np.float64(0.24999999999999997)),
 (3552, np.float64(0.24999999999999997)),
 (3859, np.float64(0.24999999999999997)),
 (4134, np.float64(0.24999999999999997)),
 (4293, np.float64(0.24999999999999997)),
 (4496, np.float64(0.24999999999999997)),
 (4675, np.float64(0.24999999999999997)),
 (4760, np.float64(0.24999999999999997)),
 (4923, np.float64(0.24999999999999997)),
 (5295, np.float64(0.24999999999999997)),
 (5697, np.float64(0.24999999999999997)),
 (6142, np.float64(0.24999999999999997)),
 (6278, np.float64(0.24999999999999997)),
 (6553, np.float64(0.24999999999999997)),
 (6573, np.float64(0.24999999999999997)),
 (7212, np.float64(0.24999999999999997)),
 (7684, np.float64(0.24999999999999997)),
 (7789, np.float64(0.24999999999999997)),
 (8296, np.float64(0.24999999999999997)),
 (3812, np.float64(0.2491364395612199)),
 (4333, np.float64(0.2491364395612199)),
 (5102, np.float64(0.2491364395612199)),
 (6084, np.float64(0.2491364395612199)),
 (7639, np.float64(0.24913643956121986)),
 (8032, np.float64(0.24913643956121986)),
 (2228, np.float64(0.2480694691784169)),
 (8565, np.float64(0.2480694691784169)),
 (2616, np.float64(0.2449489742783178)),
 (3143, np.float64(0.2449489742783178)),
 (5841, np.float64(0.24494897427831777)),
 (7721, np.float64(0.24494897427831777)),
 (62, np.float64(0.2439750182371333)),
 (105, np.float64(0.2439750182371333)),
 (128, np.float64(0.2439750182371333)),
 (345, np.float64(0.2439750182371333)),
 (617, np.float64(0.2439750182371333)),
 (856, np.float64(0.2439750182371333)),
 (971, np.float64(0.2439750182371333)),
 (1259, np.float64(0.2439750182371333)),
 (1396, np.float64(0.2439750182371333)),
 (1685, np.float64(0.2439750182371333)),
 (1826, np.float64(0.2439750182371333)),
 (2549, np.float64(0.2439750182371333)),
 (2556, np.float64(0.2439750182371333)),
 (2644, np.float64(0.2439750182371333)),
 (2736, np.float64(0.2439750182371333)),
 (2771, np.float64(0.2439750182371333)),
 (2907, np.float64(0.2439750182371333)),
 (3733, np.float64(0.2439750182371333)),
 (4418, np.float64(0.2439750182371333)),
 (5141, np.float64(0.2439750182371333)),
 (5148, np.float64(0.2439750182371333)),
 (5186, np.float64(0.2439750182371333)),
 (5649, np.float64(0.2439750182371333)),
 (5861, np.float64(0.2439750182371333)),
 (6381, np.float64(0.2439750182371333)),
 (6779, np.float64(0.2439750182371333)),
 (6967, np.float64(0.2439750182371333)),
 (7025, np.float64(0.2439750182371333)),
 (7659, np.float64(0.2439750182371333)),
 (7914, np.float64(0.2439750182371333)),
 (8269, np.float64(0.2439750182371333)),
 (8731, np.float64(0.2439750182371333)),
 (3496, np.float64(0.24096579867074966)),
 (5781, np.float64(0.24096579867074966)),
 (7521, np.float64(0.24096579867074966)),
 (5105, np.float64(0.23904572186687872)),
 (7731, np.float64(0.23904572186687872)),
 (370, np.float64(0.23836564731139806)),
 (446, np.float64(0.23836564731139806)),
 (958, np.float64(0.23836564731139806)),
 (1003, np.float64(0.23836564731139806)),
 (1112, np.float64(0.23836564731139806)),
 (1783, np.float64(0.23836564731139806)),
 (2016, np.float64(0.23836564731139806)),
 (2266, np.float64(0.23836564731139806)),
 (3054, np.float64(0.23836564731139806)),
 (3382, np.float64(0.23836564731139806)),
 (3952, np.float64(0.23836564731139806)),
 (4190, np.float64(0.23836564731139806)),
 (5810, np.float64(0.23836564731139806)),
 (5985, np.float64(0.23836564731139806)),
 (6531, np.float64(0.23836564731139806)),
 (6712, np.float64(0.23836564731139806)),
 (7244, np.float64(0.23836564731139806)),
 (7434, np.float64(0.23836564731139806)),
 (7539, np.float64(0.23836564731139806)),
 (7578, np.float64(0.23836564731139806)),
 (8103, np.float64(0.23836564731139806)),
 (8111, np.float64(0.23836564731139806)),
 (8532, np.float64(0.23836564731139806)),
 (8628, np.float64(0.23836564731139806)),
 (3195, np.float64(0.23717082451262841)),
 (6429, np.float64(0.23717082451262841)),
 (7450, np.float64(0.23717082451262841)),
 (221, np.float64(0.23312620206007845)),
 (693, np.float64(0.23312620206007845)),
 (1337, np.float64(0.23312620206007845)),
 (1658, np.float64(0.23312620206007845)),
 (2197, np.float64(0.23312620206007845)),
 (2281, np.float64(0.23312620206007845)),
 (2332, np.float64(0.23312620206007845)),
 (2617, np.float64(0.23312620206007845)),
 (2619, np.float64(0.23312620206007845)),
 (3072, np.float64(0.23312620206007845)),
 (3961, np.float64(0.23312620206007845)),
 (4006, np.float64(0.23312620206007845)),
 (4239, np.float64(0.23312620206007845)),
 (4483, np.float64(0.23312620206007845)),
 (4559, np.float64(0.23312620206007845)),
 (5456, np.float64(0.23312620206007845)),
 (5529, np.float64(0.23312620206007845)),
 (5615, np.float64(0.23312620206007845)),
 (5748, np.float64(0.23312620206007845)),
 (5767, np.float64(0.23312620206007845)),
 (5813, np.float64(0.23312620206007845)),
 (6045, np.float64(0.23312620206007845)),
 (6351, np.float64(0.23312620206007845)),
 (6446, np.float64(0.23312620206007845)),
 (6497, np.float64(0.23312620206007845)),
 (6550, np.float64(0.23312620206007845)),
 (6700, np.float64(0.23312620206007845)),
 (6977, np.float64(0.23312620206007845)),
 (7454, np.float64(0.23312620206007845)),
 (7947, np.float64(0.23312620206007845)),
 (8024, np.float64(0.23312620206007845)),
 (8389, np.float64(0.23312620206007845)),
 (8510, np.float64(0.23312620206007845)),
 (8751, np.float64(0.23312620206007845)),
 (8754, np.float64(0.23312620206007845)),
 (342, np.float64(0.23094010767585027)),
 (2662, np.float64(0.23094010767585027)),
 (7014, np.float64(0.23094010767585027)),
 (8361, np.float64(0.23094010767585027)),
 (8403, np.float64(0.23094010767585027)),
 (8679, np.float64(0.2300894966542111)),
 (377, np.float64(0.22821773229381923)),
 (541, np.float64(0.22821773229381923)),
 (673, np.float64(0.22821773229381923)),
 (977, np.float64(0.22821773229381923)),
 (1002, np.float64(0.22821773229381923)),
 (1691, np.float64(0.22821773229381923)),
 (1728, np.float64(0.22821773229381923)),
 (1765, np.float64(0.22821773229381923)),
 (1950, np.float64(0.22821773229381923)),
 (2505, np.float64(0.22821773229381923)),
 (2683, np.float64(0.22821773229381923)),
 (2996, np.float64(0.22821773229381923)),
 (3603, np.float64(0.22821773229381923)),
 (3916, np.float64(0.22821773229381923)),
 (4223, np.float64(0.22821773229381923)),
 (4442, np.float64(0.22821773229381923)),
 (4450, np.float64(0.22821773229381923)),
 (4713, np.float64(0.22821773229381923)),
 (4857, np.float64(0.22821773229381923)),
 (5028, np.float64(0.22821773229381923)),
 (5145, np.float64(0.22821773229381923)),
 (5146, np.float64(0.22821773229381923)),
 (5442, np.float64(0.22821773229381923)),
 (5546, np.float64(0.22821773229381923)),
 (5980, np.float64(0.22821773229381923)),
 (6407, np.float64(0.22821773229381923)),
 (6548, np.float64(0.22821773229381923)),
 (7091, np.float64(0.22821773229381923)),
 (7134, np.float64(0.22821773229381923)),
 (7171, np.float64(0.22821773229381923)),
 (7241, np.float64(0.22821773229381923)),
 (7359, np.float64(0.22821773229381923)),
 (8077, np.float64(0.22821773229381923)),
 (45, np.float64(0.22360679774997896)),
 (117, np.float64(0.22360679774997896)),
 (857, np.float64(0.22360679774997896)),
 (917, np.float64(0.22360679774997896)),
 (1150, np.float64(0.22360679774997896)),
 (1340, np.float64(0.22360679774997896)),
 (1468, np.float64(0.22360679774997896)),
 (1841, np.float64(0.22360679774997896)),
 (1971, np.float64(0.22360679774997896)),
 (2126, np.float64(0.22360679774997896)),
 (2239, np.float64(0.22360679774997896)),
 (2451, np.float64(0.22360679774997896)),
 (2559, np.float64(0.22360679774997896)),
 (2560, np.float64(0.22360679774997896)),
 (2935, np.float64(0.22360679774997896)),
 (4123, np.float64(0.22360679774997896)),
 (4355, np.float64(0.22360679774997896)),
 (4472, np.float64(0.22360679774997896)),
 (4583, np.float64(0.22360679774997896)),
 (5288, np.float64(0.22360679774997896)),
 (5446, np.float64(0.22360679774997896)),
 (5818, np.float64(0.22360679774997896)),
 (6067, np.float64(0.22360679774997896)),
 (6303, np.float64(0.22360679774997896)),
 (6752, np.float64(0.22360679774997896)),
 (7311, np.float64(0.22360679774997896)),
 (7581, np.float64(0.22360679774997896)),
 (7830, np.float64(0.22360679774997896)),
 (7969, np.float64(0.22360679774997896)),
 (8017, np.float64(0.22360679774997896)),
 (8738, np.float64(0.22360679774997896)),
 (199, np.float64(0.21926450482675733)),
 (573, np.float64(0.21926450482675733)),
 (2029, np.float64(0.21926450482675733)),
 (2606, np.float64(0.21926450482675733)),
 (2840, np.float64(0.21926450482675733)),
 (2853, np.float64(0.21926450482675733)),
 (2873, np.float64(0.21926450482675733)),
 (4919, np.float64(0.21926450482675733)),
 (5436, np.float64(0.21926450482675733)),

In [43]:
def recommend(movie):

  index = movies[movies['title']==movie].index[0]

  distance = similar[index]

  movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x:x[1])[1:6]
  for i in movies_list:

    print(movies.iloc[i[0]].title)

In [45]:
recommend("Trial By Media")

The Confession Tapes
Women Behind Bars
Elize Matsunaga: Once Upon a Crime
Killer Inside: The Mind of Aaron Hernandez
The Keepers